services:
  - type: web
    name: diagram-builder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS=false
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    preBuildCommand: apt-get update && apt-get install -y graphviz
